import Head from 'next/head';
import { useSelector } from 'react-redux';

import Layout from '../src/client/components/Layout';
import Sidebar from '../src/client/components/Sidebar';
import Header from '../src/client/components/Header';
import Section from '../src/client/components/Section';


//! update <Head> and all needed info later

export default function Home() {
  const isDarkMode = useSelector((state) => state.settings.isDarkMode);

  return (
    <div className={isDarkMode ? 'theme--dark' : 'theme--light'}>
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className="main">
        <Layout>
          <Header
            heading="Michael Doudy"
            subHeading="Software Engineer"
            text="I'm an NYC-based software engineer that works at Helbiz."
          />
          <Section heading="About" />
          <Section heading="Work" />
          <Section heading="Photography" />
          <Section heading="Contact" />
        </Layout>
        <Sidebar>
          <h2>About</h2>
          <h2>Work</h2>
          <h2>Photography</h2>
          <h2>Contact</h2>
        </Sidebar>
      </main>
    </div>
  )
}
