import React, { useRef } from 'react'
import Head from 'next/head';
import { useSelector } from 'react-redux';

import Layout from '../src/client/components/Layout';
import Sidebar from '../src/client/components/Sidebar';
import About from '../src/client/components/About';
import Header from '../src/client/components/Header';
import Section from '../src/client/components/Section';
import ProjectCard from '../src/client/components/ProjectCard';
import Gallery from '../src/client/components/Gallery';
import Contact from '../src/client/components/Contact';
import {
  sidebar,
  about,
  header,
  projectCards,
  gallery,
  contact
} from '../src/client/data/data.json';

//! update <Head> and all needed info later

export default function Home() {
  const isDarkMode = useSelector((state) => state.settings.isDarkMode);
  const sectionRefs= useRef({});

  const scrollTo = (e) => {
    if (!e.target.getAttribute('scroll-dest')) return;
    const ref = sectionRefs.current[`${e.target.getAttribute('scroll-dest').toLowerCase()}Ref`];
    if (ref) {
      ref.scrollIntoView({ behavior: 'smooth', block: 'start' })
    }
  }

  return (
    <div className={isDarkMode ? 'theme--dark' : 'theme--light'}>
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className="main">
        <Layout>
          <Header
            preHeading={header.preHeading}
            heading={header.heading}
            subHeading={header.subHeading}
            text={header.text}
            ctaText={header.ctaText}
            scrollTo={scrollTo}
          />
          <Section
            heading="About Me"
            ref={(el) => { sectionRefs.current[`${'About Me'.toLowerCase()}Ref`] = el }}
          >
            <About content={about.content} image={about.image} />
          </Section>
          <Section
            heading="Work"
            ref={(el) => { sectionRefs.current[`${'Work'.toLowerCase()}Ref`] = el }}
          >
            { projectCards.map((data, i) => (
              <ProjectCard
                key={data.title || i}
                title={data.title}
                description={data.description}
                tools={data.tools}
                links={data.links}
                image={data.image}
                showInverse={!!(i % 2)}
              />
            ))}
          </Section>
          <Section
            heading="Photography"
            ref={(el) => { sectionRefs.current[`${'Photography'.toLowerCase()}Ref`] = el }}
          >
            <Gallery images={gallery} />
          </Section>
          <Section
            heading="Contact"
            ref={(el) => { sectionRefs.current[`${'Contact'.toLowerCase()}Ref`] = el }}
          >
            <Contact
              text={contact.text}
              ctaText={contact.ctaText}
              email={contact.email}
            />
          </Section>
        </Layout>
        <Sidebar
          navHeadings={sidebar.navHeadings}
          social={sidebar.social}
          scrollTo={scrollTo}
        />
      </main>
    </div>
  )
}
